# Generated by Django 5.1.2 on 2025-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=40)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
